version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
    - zabbix-db:/var/lib/mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
  zabbix-java:
    image: zabbix/zabbix-java-gateway:alpine-7.2-latest
    container_name: zabbix-java
    restart: always
    depends_on:
    - db

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
      ZBX_JAVAGATEWAY: "zabbix-java"
    ports:
    - "10051:10051"
    restart: unless-stopped
    depends_on:
    - db
    - zabbix-java

  web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    ports:
    - "8080:8080"
    restart: unless-stopped
    depends_on:
    - zabbix-server-mysql

volumes:
  zabbix-db: {}
