version: '2'
services:
  db:
    image: mysql:8.0-oracle
    volumes:
    - zabbix-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"

  zabbix-java:
    image: zabbix/zabbix-java-gateway:alpine-7.2-latest
    restart: always
    depends_on:
    - db

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
      ZBX_JAVAGATEWAY: "zabbix-java"
    ports:
    - "10051:10051"
    restart: always
    depends_on:
    - db
    - zabbix-java

  web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
      ZBX_JAVAGATEWAY: "zabbix-java"
    ports:
    - "80:80"
    restart: always
    depends_on:
    - zabbix-server-mysql

volumes:
  zabbix-db: {}
